apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-workflow-config
  namespace: dev-workflow
data:
  NODE_ENV: production

  REPORT_PORT: "5004"
  NOTIFICATION_PORT: "5003"
  TASK_PORT: "5002"
  AUTH_PORT: "5001"

  JWT_EXPIRES_IN: "1D"

  AUTH_MONGO_URI: "mongodb://mongodb:27017/authdb"
  TASK_MONGO_URI: "mongodb://mongodb:27017/taskdb"
  NOTIFICATION_MONGO_URI: "mongodb://mongodb:27017/notificationdb"
  REPORT_MONGO_URI: "mongodb://mongodb:27017/reportdb"
