apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  namespace: dev-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      imagePullSecrets:
        - name: harbor-registry
      containers:
        - name: report-service
          image: ${HARBOR_HOST}/dev-workflow/smarttask-report-service:${DOCKER_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/reportdb"
            - name: JWT_SECRET
              value: "MySecret@123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: dev-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      imagePullSecrets:
        - name: harbor-registry
      containers:
        - name: notification-service
          image: ${HARBOR_HOST}/dev-workflow/smarttask-notification-service:${DOCKER_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 5003
          env:
            - name: PORT
              value: "5003"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/notificationdb"
            - name: JWT_SECRET
              value: "MySecret@123"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: dev-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      imagePullSecrets:
        - name: harbor-registry
      containers:
        - name: task-service
          image: ${HARBOR_HOST}/dev-workflow/smarttask-task-service:${DOCKER_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              value: "5002"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/taskdb"
            - name: JWT_SECRET
              value: "MySecret@123"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: dev-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
        - name: harbor-registry
      containers:
        - name: auth-service
          image: ${HARBOR_HOST}/dev-workflow/smarttask-auth-service:${DOCKER_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/authdb"
            - name: JWT_SECRET
              value: "MySecret@123"
            - name: JWT_EXPIRES_IN
              value: "1d"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: dev-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      imagePullSecrets:
        - name: harbor-registry
      containers:
        - name: api-gateway
          image: ${HARBOR_HOST}/dev-workflow/smarttask-api-gateway:${DOCKER_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:5001"
            - name: TASK_SERVICE_URL
              value: "http://task-service:5002"
            - name: JWT_SECRET
              value: "MySecret@123"
