[docker-server]
docker ansible_host=ec2-3-81-215-233.compute-1.amazonaws.com
[harbor-soft]
harbor-soft ansible_host=ec2-3-81-215-233.compute-1.amazonaws.com
[vault-server]
vault-server ansible_host=ec2-3-81-215-233.compute-1.amazonaws.com
[kubernetes-server]
kubernetes-server ansible_host=ec2-3-81-215-233.compute-1.amazonaws.com
