[docker-server]
docker_soft ansible_host=ec2-54-162-249-35.compute-1.amazonaws.com
[harbor-server]
harbor_soft ansible_host=ec2-54-162-249-35.compute-1.amazonaws.com
[vault-server]
vault_soft ansible_host=ec2-54-162-249-35.compute-1.amazonaws.com
[kubernetes-server]
kubernetes_soft ansible_host=ec2-54-162-249-35.compute-1.amazonaws.com
