---
- name: Install Minikube on Ubuntu EC2
  hosts: kubernetes-server
  become: yes
  vars:
    minikube_version: "v1.33.1"
    kubectl_version: "v1.30.0"
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name: [curl, wget, apt-transport-https, conntrack]
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes


    - name: Install kubectl
      get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Install Minikube
      get_url:
        url: "https://storage.googleapis.com/minikube/releases/{{ minikube_version }}/minikube-linux-amd64"
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Restart SSH Connection
      meta: restart_connection

    - name: Start Minikube with Docker driver
      become_user: ubuntu
      shell: minikube start --driver=docker --memory=4096 --cpus=2
      args:
        creates: /home/ubuntu/.minikube

    - name: Enable Minikube addons
      become_user: ubuntu
      shell: |
        minikube addons enable metrics-server
        minikube addons enable ingress
